# This is a basic workflow to help you get started with Actions

name: tag-rc
on:
  workflow_dispatch:
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      # Install Node 12
      - uses: actions/setup-node@v1
          version: 12
      - run: npm install @octokit/action
      - run: node .github/actions/create-pre-release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}